# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starttask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time started')),
            ],
        ),
        migrations.CreateModel(
            name='Stoptask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time stopped')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='date completed')),
            ],
        ),
        migrations.AddField(
            model_name='stoptask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.Task'),
        ),
        migrations.AddField(
            model_name='starttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.Task'),
        ),
    ]
