# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20161214_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='to_do_list.Task')),
            ],
        ),
        migrations.DeleteModel(
            name='Idlestart',
        ),
        migrations.DeleteModel(
            name='Idlestop',
        ),
    ]
