# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_auto_20170127_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currenttask',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='current',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='CurrentTask',
        ),
    ]
