# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0007_auto_20170203_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starttask',
            name='tasklist',
        ),
        migrations.RemoveField(
            model_name='stoptask',
            name='tasklist',
        ),
    ]
