# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0008_auto_20170208_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currenttask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='currenttask',
            name='tasklist',
        ),
        migrations.AddField(
            model_name='task',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CurrentTask',
        ),
    ]
