# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0011_auto_20170222_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juncture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name=b'time started')),
                ('juncture', models.CharField(choices=[(b'START', b'Start'), (b'STOP', b'Stop')], max_length=5)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.Task')),
            ],
        ),
        migrations.RemoveField(
            model_name='starttask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='stoptask',
            name='task',
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='currenttask',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedtasklist', to='to_do_list.Task'),
        ),
        migrations.DeleteModel(
            name='Starttask',
        ),
        migrations.DeleteModel(
            name='Stoptask',
        ),
    ]
